### ISSUE TITLE
[Bug]: Settings icons and search bar are cut-off

### ISSUE THREAD

**Issue by luah5** [SwiftcordApp/Swiftcord#157] opened 2023-05-21 20:06 UTC
### Describe the Bug

**Bug Description**
When opening Swiftcord settings on a smaller resolution screen device the search bar and sidebar icons appear to be cut off, the search bar especially.

**Expected Behavior**
The search bar and sidebar icons shouldn't be cutoff.

### Reproducing the Bug

1. Open Swiftcord
2. Open the settings
3. Notice that the search bar and icons are cutoff

### Version

0.6.1 (build 16), macOS 13.3.1 (a), from latest release

### Category

Settings

### Relevant Log Output

```shell
N/A
```

### Screenshots

<img width="828" alt="shot 1" src="https://github.com/SwiftcordApp/Swiftcord/assets/128280019/677f589a-68cf-4a45-9aab-50f9e8fdde87">

### Additional Info

N/A

**Comment by cryptoAlgorithm** [comment] 2023-05-28 01:39
Hmmm, the people at CodeEdit also seemed to have encountered the same issue, and I've seen it happen in Swiftcord on someone else's Mac. Could it have been something to do with the scaling factor? One thing in common with all these occurrences was that they were using a non-default scaling factor. It doesn't seem to have anything to do with the resolution itself or whether the display is retina, as my external 4k display doesn't exhibit this at the macOS default scaling.

**Comment by luah5** [comment] 2023-05-28 05:33
I don't think so, here's a screenshot of my settings
<img width="827" alt="System Settings Displays" src="https://github.com/SwiftcordApp/Swiftcord/assets/128280019/3f96fe8b-befb-40ba-8414-2937a69e35d2">

**Comment by Infinivibex** [comment] 2023-06-10 16:17
Even on a non-default scaling factor, I don't seem to have that issue.

<img width="222" alt="Screenshot 2023-06-10 at 09 15 49" src="https://github.com/SwiftcordApp/Swiftcord/assets/127473253/bb34e37b-efca-4585-828d-48e11a0f2762">
<img width="496" alt="Screenshot 2023-06-10 at 09 16 05" src="https://github.com/SwiftcordApp/Swiftcord/assets/127473253/7c26e56d-5da2-4fdf-9517-285064e2caf6">

**Comment by cryptoAlgorithm** [comment] 2023-06-18 09:52
@Infinivibex Thanks for testing. The thing is this doesn't appear to occur all the time, only with some display configurations. And most notably, this only seems to happen when the app is rendered on a non-Apple display set on non-default scaling, but not always.

**Comment by cryptoAlgorithm** [comment] 2023-09-25 10:50
Closing as this appears to be too isolated for a fix. I cannot reproduce this on any of my monitors (internal 14" display, external 32" LG 4k UltraFine) with any scaling. It seems to be isolated to a very small group of users, and logs don't seem to show anything out of the ordinary. Sorry!

**Closed by cryptoAlgorithm** 2023-09-25 10:50 UTC
Labels: bug, ui
