### ISSUE TITLE
Stuck on "Establishing Gateway connection"

### ISSUE THREAD

**Issue by Melonking906** [SwiftcordApp/Swiftcord#12] opened 2022-04-28 18:45 UTC
Trying this out as a native alternative to Ripcord (by cancel.fm)! Looks like a cool project!
When I open the app it seems to just sit on "Establishing Gateway connection" without progressing.

Looking at its network traffic in LittleSnitch, it sends a request to "discord.gg" when first launched but it never gets a reply and it does not make any more requests.

Swiftcord v0.2.2(3) - Pre-built provided on GitHub
MacOS v12.3.1
Macbook Pro M1 Pro

**Comment by cryptoAlgorithm** [comment] 2022-04-29 04:12
Ok, are you comfortable running the app in Xcode? That way I can get useful logs that might help with the issue. Alternatively, you can look into the console logs and filter by Swiftcord, but it tends to get drowned in the flood of logs.

**Comment by cryptoAlgorithm** [comment] 2022-04-29 04:16
@Melonking906 joining the discord server [here](https://discord.gg/gUhfBnGBCs) would allow me to respond to you faster, important for debugging!

**Comment by cryptoAlgorithm** [comment] 2022-04-30 06:15
I'll close the issue in a few day's time if there's no more input from @Melonking906, with the assumption the issue is now resolved.

**Comment by cryptoAlgorithm** [comment] 2022-05-05 02:36
No more input was received from the OP - closing the issue.

**Comment by EvanLuo42** [comment] 2022-05-27 06:31
Log:
`Error when receiving: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 57 - Socket is not connected)`
 
Perhaps it is caused by proxy. Maybe add custom proxy address setting would solve this, because of the GFW. I think that the app network traffic default not through ClashX or other proxy app.

**Comment by cryptoAlgorithm** [comment] 2022-05-27 06:49
Yeah, this log happens all the time when the internet connection isn't available. Could you see if it works without your proxy enabled?

**Comment by EvanLuo42** [comment] 2022-05-27 06:50
> Yeah, this log happens all the time when the internet connection isn't available. Could you see if it works without your proxy enabled?

No, it couldn't work.

**Comment by EvanLuo42** [comment] 2022-05-27 06:51
> Yeah, this log happens all the time when the internet connection isn't available. Could you see if it works without your proxy enabled?

My location is in China, so I even couldn't connect to the Discord server by official client.

**Comment by EvanLuo42** [comment] 2022-05-27 06:54
> Yeah, this log happens all the time when the internet connection isn't available. Could you see if it works without your proxy enabled?

And I read the proxy log. It said it went through the proxy. (Now the proxy is enabled.) I think it shouldn't be proxy's wrong.

**Comment by cryptoAlgorithm** [comment] 2022-05-27 06:55
Ok, I see. What proxy are you using, and does it work if you use the discord client in a browser?

**Comment by EvanLuo42** [comment] 2022-05-27 06:57
> Ok, I see. What proxy are you using, and does it work if you use the discord client in a browser?

I'm using ClashX and the subscription is from `cloud.faster.buzz`. It works fine in discord client using Safari.

**Comment by cryptoAlgorithm** [comment] 2022-05-27 06:58
<img width="780" alt="Screenshot 2022-05-27 at 2 58 16 PM" src="https://user-images.githubusercontent.com/64193267/170647769-81203b5f-2313-4d69-b4a2-793aac1d70e3.png">

Could you use the built in proxy settings in macOS to connect to your proxy? It might work that way.

**Comment by EvanLuo42** [comment] 2022-05-27 06:59
> Ok, I see. What proxy are you using, and does it work if you use the discord client in a browser?

I have seen this kind of problem before while using Infuse. Perhaps it is caused by ClashX. Because it also worked fine if I turned off ClashX or using other proxy app.

**Comment by EvanLuo42** [comment] 2022-05-27 07:00
> <img alt="Screenshot 2022-05-27 at 2 58 16 PM" width="780" src="https://user-images.githubusercontent.com/64193267/170647769-81203b5f-2313-4d69-b4a2-793aac1d70e3.png">
> 
> Could you use the built in proxy settings in macOS to connect to your proxy? It might work that way.

My current macOS setting had enabled proxy.

**Comment by EvanLuo42** [comment] 2022-05-27 07:01
> <img alt="Screenshot 2022-05-27 at 2 58 16 PM" width="780" src="https://user-images.githubusercontent.com/64193267/170647769-81203b5f-2313-4d69-b4a2-793aac1d70e3.png">
> 
> Could you use the built in proxy settings in macOS to connect to your proxy? It might work that way.

Maybe I can try to use other proxy app.

**Comment by EvanLuo42** [comment] 2022-05-27 07:03
> Normally, native apps should follow the system proxy setting, but I might be wrong. I'll keep this issue open for input from other contributors.

Ok, thank you, and I'm going to try to use other proxy app. If it worked, I'll tell you.

**Comment by EvanLuo42** [comment] 2022-05-27 07:07
> Normally, native apps should follow the system proxy setting, but I might be wrong. I'll keep this issue open for input from other contributors.

I'm wrong, it was not the issue of ClashX. I changed another proxy app call QV2ray, it still stuck on `Establishing Gateway connection.`

**Comment by EvanLuo42** [comment] 2022-05-27 07:35
> Ok. Firstly what swiftcord version are you using? Next, are there any interesting thing in the log that might tell us why it can't open a web socket connection?

It’s 0.4.0. And I only found the error I showed before. Let me check what is in front of that error.

**Comment by EvanLuo42** [comment] 2022-05-27 07:42
> Ok. Firstly what swiftcord version are you using? Next, are there any interesting thing in the log that might tell us why it can't open a web socket connection?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62578958/170653474-9005b319-1a49-43c0-b0c3-8d288eb0a71c.png">
I don't know which log is useful

**Comment by cryptoAlgorithm** [comment] 2022-05-27 11:42
Could you run it from Xcode? That would give better logs. Also the logs that aren't errors are important too, so do not just filter by errors.

**Comment by EvanLuo42** [comment] 2022-05-27 11:59
> Could you run it from Xcode? That would give better logs. Also the logs that aren't errors are important too, so do not just filter by errors.

Ok, I'm fetching dependencies.

**Comment by EvanLuo42** [comment] 2022-05-27 13:32
> Could you run it from Xcode? That would give better logs. Also the logs that aren't errors are important too, so do not just filter by errors.

It's a little bit hard for me to fetch dependencies I think. I don't know why the package manager is that slow.

**Comment by cryptoAlgorithm** [comment] 2022-05-27 13:50
Could it be because of your proxy? It fetches in a few seconds for me

**Comment by EvanLuo42** [comment] 2022-05-27 13:54
> Could it be because of your proxy? It fetches in a few seconds for me

It should be the proxy problem. Never solved. The same when I was programming iOS app.

**Comment by 0ihsan** [comment] 2022-05-28 11:17
I am proxying my macOS network through my iPhone and having the same issue.

**Comment by cryptoAlgorithm** [comment] 2022-05-28 12:07
@EvanLuo42 As I'm unable to reproduce both your situation and this bug, I can't work on a potential fix. I'll mark this won't fix for now, but if someone can provide more detailed logs on what's going on or tell me how I can reproduce it, I'll take a look at it.

**Comment by cryptoAlgorithm** [comment] 2022-05-28 12:08
@0ihsan Hi! can i get more details like the version of swiftcord youre using, as well as logs relevant to the issue?

**Comment by EvanLuo42** [comment] 2022-05-28 12:21
Sorry, I didn’t explain in a clear way. I’m going to explain it more to build my network environment. If you are willing to tell me your email address, I’ll send you my proxy address and tell you how to connect to it(if you don’t know what is clash).

**Comment by cryptoAlgorithm** [comment] 2022-05-28 15:17
@EvanLuo42 Ah no worries. You can send it to my GitHub email, or thru a Discord DM.

**Comment by cryptoAlgorithm** [comment] 2022-06-04 04:46
@EvanLuo42 Lets move this to a discussion so I can close this issue.

**Closed by cryptoAlgorithm** 2022-06-04 04:46 UTC
Labels: bug
