### ISSUE TITLE
[Bug]: Symbols not rendered correctly

### ISSUE THREAD

**Issue by domenicoblanco** [SwiftcordApp/Swiftcord#123] opened 2022-10-18 06:32 UTC
### Describe the Bug

**Bug Description**
Symbols as ** are not rendered correctly during the startup phase 

**Actual Behaviour**
!!{asterisks}!!

**Expected Behavior**
**

### Reproducing the Bug

1. Just login

### Version

0.5.1

### Category

Connection

### Screenshots

<img width="1012" alt="Screenshot 2022-10-18 at 08 15 37" src="https://user-images.githubusercontent.com/9018104/196353066-b1edb9a1-db0b-40ea-863a-18a9a900b356.png">

**Comment by cryptoAlgorithm** [comment] 2022-10-18 11:27
@domenicoblanco this is a dupe of #119: Swiftcord uses the built in markdown parsing in `Text`, which doesn't support certain extensions of markdown that Discord's using to render those rich text.

**Closed by cryptoAlgorithm** 2022-10-18 11:27 UTC
Labels: bug, triage

**Comment by domenicoblanco** [comment] 2022-10-18 12:50
Sorry for the duplicate, didn't notice that #119 was about Markdown in general
