### ISSUE TITLE
Channel visibility permissions are not respected

### ISSUE THREAD

**Issue by frozenfleris** [SwiftcordApp/Swiftcord#137] opened 2023-02-10 21:20 UTC
### Describe the Bug

**Bug Description**
On a discord server, even if you don't have the perms to see certain channels on a given server, they can still be shown.

**Actual Behaviour**
You can view the server's hidden channels, without perms.

**Expected Behavior**
If you do not have permission to view the channel, it should be hidden

### Reproducing the Bug

1... Open Swiftcord
2... Join a server (any discord server)
3... look at the channels list

### Version

0.5.0

### Category

Other

**Comment by TerminalFi** [comment] 2023-02-11 05:28
@frozenfleris To be fair, Swiftcord is a client and it should be the servers responsibility to not disclose that information. I would say the bug lies with Discord. But.... I can see how the enduser might not want to see those servers

**Comment by frozenfleris** [comment] 2023-02-11 17:47
Even if the channels are hidden on the regular discord client, it shows up on swiftcord's end. That's where I'm getting at with this.

**Comment by TerminalFi** [comment] 2023-02-11 18:31
Sure, I get it.

**Comment by TerminalFi** [comment] 2023-02-12 16:02
> Even if the channels are hidden on the regular discord client, it shows up on swiftcord's end. That's where I'm getting at with this.

Btw, this would be a duplicate of #26

**Comment by cryptoAlgorithm** [comment] 2023-02-15 01:54
Hi, thanks for reporting this. This isn't a bug, as Discord's API exposes all channels in the server, regardless if the user has permissions to view them. It's the responsibility of the client to hide those channels from the user, but that hasn't been implemented in Swiftcord yet.

**Comment by cryptoAlgorithm** [comment] 2023-02-16 05:57
@frozenfleris Looks like that's clarified, I'll be closing this issue then :D

**Closed by cryptoAlgorithm** 2023-02-16 05:57 UTC
Labels: backend
