### ISSUE TITLE
[Enhancement]: Hide the private channels

### ISSUE THREAD

**Issue by cjwcommuny** [SwiftcordApp/Swiftcord#117] opened 2022-10-10 06:42 UTC
### Describe Your Request

Currently Swiftcord doesn't hide the private channel which users can't access, but give the error prompt as follows:

<img width="586" alt="CleanShot-2022-10-10-14 39 54" src="https://user-images.githubusercontent.com/23581749/194810123-e5c8125a-fe51-44ad-9cf9-b8814fed0846.png">

This can be confusing. It would be better to filter out the inaccessible channel for users.

### Category

Other

### Other Category

Channel

### Screenshots

<img width="556" alt="CleanShot-2022-10-10-14 41 37" src="https://user-images.githubusercontent.com/23581749/194810328-b7e7492e-4594-4ab3-82a9-d0d5d12cba16.png">

In this figure, the `tokio-dev-private` should be filtered out.

**Comment by cryptoAlgorithm** [comment] 2022-10-14 03:20
Many have pointed out this issue, but there's one blocking issue thats preventing this enhancement from going forward: roles and channel perm overrides haven't been implemented, so at this moment its impossible to determine the channels to hide. Roles would have to be fully implemented first for this to be implemented.

**Comment by cryptoAlgorithm** [comment] 2022-10-15 05:49
Closing as a duplicate of #26

**Closed by cryptoAlgorithm** 2022-10-15 05:49 UTC
Labels: enhancement
